---
#Ticks between each bossbar update:
update_delay: 2

#The time (IN SECONDS) to capture KOTH:
capture_time: 300

#Should the plugin display KOTH information on the bossbar (top of screen) (on/off):
bossbar: on

#Should the plugin display KOTH information above the hotbar (bottom of screen) (on/off):
hotbar_popups: off

#The commands that will be executed when the KOTH event has ended, {PLAYER} will be replaced with the name of the winner:
reward_commands:
  - "give {PLAYER} diamond 64"
  - "give {PLAYER} obsidian 64"

#Times when a KOTH event should automatically start (format: HOUR.MINUTE) (Leave blanc if you dont want to use this):
start_times:
  - 17.0 #For example, this will automatically start a KOTH event at 5PM

#The message that will broadcast when a KOTH event starts, {ARENA_NAME} will be replaced with the name of the arena:
start_message: "\n§7[§bKOTH§7] §a§l{ARENA_NAME} KOTH has started!\n"

#The messgae that will be broadcasted when a KOTH event ends, {PLAYER} will be replaced with the name of the winner:
end_message: "§7[§bKOTH§7] §a§lKOTH event has ended and {PLAYER} has won!"


#Webhooks are a way to automatically send discord messages when KOTH start/ends.
#Change whatever you want here. To remove something, just leave it blank.
#Everything that is already in here is just here as an example.

webhook_link:

start_webhook:
  username: "KOTH-Announcer"
  avatar-url: "https://www.giantbomb.com/a/uploads/original/8/87790/3092558-h1_koth.png"
  mention: "@everyone" #To mention a role, do <@&ROLE_ID>, to mention a person do <@USER_ID>
  title: "KOTH"
  description: "A new {ARENA_NAME} KOTH has **started**!"
  fields: #You can change 'Go to' and 'Rewards' to whatever you want. You can also change them, remove them or add more fields.
    Go to: "{COORDS}"
    Rewards: "64 diamonds, 64 obsidian"
  thumnail-url: "https://static.comicvine.com/uploads/original/11136/111367279/6985185-king%20of%20the%20hill.jpg"
  image-url: "https://static.comicvine.com/uploads/original/11136/111367279/6985185-king%20of%20the%20hill.jpg"
  footer: "King Of The Hill (KOTH)"
  footer-icon-url: "https://www.giantbomb.com/a/uploads/original/8/87790/3092558-h1_koth.png"

end_webhook:
  username: "KOTH-Announcer"
  avatar-url: "https://www.giantbomb.com/a/uploads/original/8/87790/3092558-h1_koth.png"
  mention:  #To mention a role, do <@&ROLE_ID>, to mention a person do <@USER_ID>
  title: "KOTH"
  description: "The KOTH event has **ended**!"
  fields: #You can change 'Winner' and 'Rewards' to whatever you want. You can also change them, remove them or add more fields.
    Winner: "{PLAYER}"
    Rewards: "64 diamonds, 64 obsidian"
  thumnail-url: "https://static.comicvine.com/uploads/original/11136/111367279/6985185-king%20of%20the%20hill.jpg"
  image-url: "https://static.comicvine.com/uploads/original/11136/111367279/6985185-king%20of%20the%20hill.jpg"
  footer: "King Of The Hill (KOTH)"
  footer-icon-url: "https://www.giantbomb.com/a/uploads/original/8/87790/3092558-h1_koth.png"
...
